spring.application.name=bff-service-new


# Server port
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=${JWT_EXPIRATION:900000}

auth.service.url=${AUTH_SERVICE_URL:https://demo-authservice-hdfc-mvp.onrender.com}
journey.service.url=${CORE_SERVICE_URL:https://demo-customer-journey-service.onrender.com}
auth.service.health.url=${AUTH_SERVICE_URL:http://microservices-lb-1153792204.us-east-1.elb.amazonaws.com/api/v1/health}

#service client for microservice
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Disable default login form
spring.security.user.name=disabled
spring.security.user.password=disabled


# Enable health endpoint
management.endpoints.web.exposure.include=health,info

# Always show health details (useful for debugging)
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator


# Resilience4j config
resilience4j.circuitbreaker.instances.authServiceCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.authServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.authServiceCB.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.authServiceCB.wait-duration-in-open-state=10s

# Retry configuration for Auth Service
resilience4j.retry.instances.authServiceRetry.max-attempts=3
resilience4j.retry.instances.authServiceRetry.wait-duration=2s
resilience4j.retry.instances.authServiceRetry.retry-exceptions=java.net.SocketTimeoutException,org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.authServiceRetry.ignore-exceptions=org.springframework.web.client.HttpClientErrorException$Unauthorized

# ===============================
# LOGGING LEVEL CONFIGURATION
# ===============================

logging.level.root=INFO
logging.level.com.hdfc.bff=DEBUG

#eureka server register
eureka.client.service-url.defaultZone=https://log-analysis-service-registry.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
