# ===============================
# APPLICATION
# ===============================
spring.application.name=customer-journey-service
server.port=8083
spring.devtools.restart.enabled=false

# Active Profile
spring.profiles.active=local


# ===============================
# MONGODB CONFIGURATION
# ===============================
spring.data.mongodb.uri=mongodb+srv://dassekhar2002_db_user:Chandra@loganalysis.adppuew.mongodb.net/HDFC_LOG_ANALYSIS
spring.data.mongodb.database=HDFC_LOG_ANALYSIS
spring.data.mongodb.auto-index-creation=true


# ===============================
# SPRING MVC
# ===============================
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


# ===============================
# KAFKA CONFIGURATION
# ===============================
# spring.kafka.bootstrap-servers=ec2-13-222-103-15.compute-1.amazonaws.com:9092
spring.kafka.bootstrap-servers=ec2-100-51-158-74.compute-1.amazonaws.com:9092

# Consumer
spring.kafka.consumer.group-id=customer-journey-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# ===============================
# DEBEZIUM CONFIG
# ===============================
debezium.url=http://13.222.26.180:8084

# IMPORTANT: FULL REPLICA SET URI (NOT +srv)
debezium.mongodb.uri=mongodb://dassekhar2002_db_user:Chandra@ac-3uynemx-shard-00-00.adppuew.mongodb.net:27017,ac-3uynemx-shard-00-01.adppuew.mongodb.net:27017,ac-3uynemx-shard-00-02.adppuew.mongodb.net:27017/HDFC_LOG_ANALYSIS?ssl=true&replicaSet=atlas-gf7ljl-shard-0&authSource=admin&retryWrites=true&w=majority


# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.mongodb.driver=INFO
logging.level.com.hdfc.log.customerjourney=INFO


# ===============================
# YAML CONFIG IMPORT
# ===============================
spring.config.import=optional:classpath:field-mapping.yml


# ===============================
# KAFKA RESILIENCE CONFIG
# ===============================
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.concurrency=1
spring.kafka.listener.ack-mode=record
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.reconnect.backoff.max.ms=10000
spring.kafka.consumer.properties.session.timeout.ms=15000
spring.kafka.consumer.properties.request.timeout.ms=20000


# ===============================
# ACTUATOR (PREVENT RENDER CRASH)
# ===============================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.kafka.enabled=false

#eureka server register
eureka.client.service-url.defaultZone=https://log-analysis-service-registry.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
